added step, now failure is missing method within location
Failures:

  1) Browse Lower Taxonomies Browsing Africa a location "South Africa"
-> the lower taxonomies should be "Cape Town, Table Mountain National
Park"
     Failure/Error: Then the lower taxonomies should be "Cape Town,
Table Mountain National Park"
     NoMethodError:
       undefined method `get_lower' for #<Location:0x00000103067698
@name="South Africa">
     # spec/steps/location_steps.rb:6:in `block in <top (required)>'
     # ./spec/acceptance/browse_lower_taxonomies.feature:4:in `block (6
levels) in run'
     # ./spec/acceptance/browse_lower_taxonomies.feature:3:in `each'
     # ./spec/acceptance/browse_lower_taxonomies.feature:3:in `block (5
levels) in run'
     # ./spec/acceptance/browse_lower_taxonomies.feature:4:in `the
lower taxonomies should be "Cape Town, Table Mountain National Park"'

Finished in 0.00156 seconds
1 example, 1 failure